### ISSUE TITLE
How to draw a simple repeating grid layout

### ISSUE THREAD

**Issue by leesiongchan** [sylvainpolletvillard/postcss-grid-kiss#10]
```css
.wrapper {
  display: grid;
  grid-template-columns: 100px 100px 100px;
  grid-gap: 10px;
  background-color: #fff;
  color: #444;
}
```

http://codepen.io/rachelandrew/pen/BNXyQa

In most cases we want it to be repeating without designing the `grid-area`, can we do that with `grid-kiss`?
