### ISSUE TITLE
Error when rows are delimited by single quotes

### ISSUE THREAD

**Issue by LeoColomb** [sylvainpolletvillard/postcss-grid-kiss#14]
[That line](https://github.com/sylvainpolletvillard/postcss-grid-kiss/blob/ae2863de653deb05016008ef0cc6680d8557985e/lib/parse.js#L14) excludes the usage of single-quotes.

Thus the following do not work:

```css
body {
	grid-kiss:
		'+-------------------------------+      '
		'|           header ↑            | 120px'
		'+-------------------------------+      '
		'                                       '
		'+-- 30% ---+  +--- auto --------+      '
		'| .sidebar |  |       main      | auto '
		'+----------+  +-----------------+      '
		'                                       '
		'+-------------------------------+      '
		'|              ↓                | 60px '
		'|         → footer ←            |      '
		'+-------------------------------+      '
}
```
